project_id = "cidoydrpqzpiqewultok"

[functions.accept-admin-invite]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false

[functions.meta-auth]
verify_jwt = false

[functions.social-publish]
verify_jwt = false

[functions.social-scheduler]
verify_jwt = false

[functions.create-team-member]
verify_jwt = false

[functions.trello-push]
verify_jwt = false

[functions.trello-sync]
verify_jwt = false

[functions.send-admin-invite]
verify_jwt = false

[functions.delete-auth-user]
verify_jwt = false
